# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:7145/membership/onboarding/regularpatron
Content-Type: application/json
{
  "name": "Mandar Dharmadhikari",
  "email": "mandar@gmail.com",
  "gender": "Male",
  "dateOfBirth": "1990-07-03",
  "address": {
    "buildingNumber": "B1",
    "streetName": "202 Indraprastha, Moshi Alandi Road",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "zipCode": "412105"
  },
  "identityDocuments": [
    {
      "name": "IdentityDocument.pdf",
      "documentType": "PersonalId",
      "contentType": "application/pdf",
      "content": "somedata"
    },
    {
      "name": "AddressProof.pdf",
      "documentType": "AddressProof",
      "contentType": "application/pdf",
      "content": "somedata"
    }
  ]
}

###
POST https://localhost:7145/membership/onboarding/patron
Content-Type: application/json
{
  "name": "Mandar Dharmadhikari",
  "email": "mandar@gmail.com",
  "gender": "Male",
  "dateOfBirth": "1990-07-03",
  "patronType": "Regular"
}
###
GET https://localhost:7145/membership/onboarding/patron/968b05dc-3727-499f-85a2-6e1509e8723e

###
PUT https://localhost:7145/membership/onboarding/patron/0047cef1-7bc6-4933-832e-ddfbdb6cbd3a/address
Content-Type: application/json
{
  "buildingNumber": "B1",
  "streetName": "202 Indraprastha, Moshi Alandi Road",
  "city": "Pune",
  "state": "Maharashtra",
  "country": "India",
  "zipCode": "412105"
}
