// <auto-generated />
using System;
using LMS.Modules.Membership.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMS.Modules.Membership.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MembershipDbContext))]
    [Migration("20250406164353_AddedBuildingNumberToAddress")]
    partial class AddedBuildingNumberToAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("membership")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LMS.Modules.Membership.Domain.PatronAggregate.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("country");

                    b.Property<Guid>("PatronId")
                        .HasColumnType("uuid")
                        .HasColumnName("patron_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.HasIndex("PatronId")
                        .IsUnique();

                    b.ToTable("addresses", "membership");
                });

            modelBuilder.Entity("LMS.Modules.Membership.Domain.PatronAggregate.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<Guid>("PatronId")
                        .HasColumnType("uuid")
                        .HasColumnName("patron_id");

                    b.HasKey("Id");

                    b.HasIndex("PatronId");

                    b.ToTable("documents", "membership", t =>
                        {
                            t.HasCheckConstraint("ck_document_content_type", "content_type IN ('application/pdf', 'application/jpg', 'application/jpeg')");

                            t.HasCheckConstraint("ck_document_document_type", "document_type IN ('PersonalId', 'AcademicsId','AddressProof')");
                        });
                });

            modelBuilder.Entity("LMS.Modules.Membership.Domain.PatronAggregate.Patron", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_id");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("PatronType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("patron_type");

                    b.HasKey("Id");

                    b.HasIndex("AccessId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("patrons", "membership", t =>
                        {
                            t.HasCheckConstraint("ck_patrons_patron_type", "patron_type in ('Regular', 'Research')");
                        });
                });

            modelBuilder.Entity("LMS.Modules.Membership.Domain.PatronAggregate.Address", b =>
                {
                    b.HasOne("LMS.Modules.Membership.Domain.PatronAggregate.Patron", null)
                        .WithOne("Address")
                        .HasForeignKey("LMS.Modules.Membership.Domain.PatronAggregate.Address", "PatronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Modules.Membership.Domain.PatronAggregate.Document", b =>
                {
                    b.HasOne("LMS.Modules.Membership.Domain.PatronAggregate.Patron", null)
                        .WithMany("IdentityDocuments")
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LMS.Modules.Membership.Domain.PatronAggregate.Patron", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("IdentityDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
