name: LMS Mutation Testing Pipeline

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Install local tools
      run: dotnet tool restore
    
    - name: Run mutation Tests
      run: dotnet stryker -s LMS.sln -f stryker-config.json --break 80